### ISSUE TITLE
System (OS) is not considered in coinstallation rate for guid-guid recommendations.

### ISSUE THREAD

**Issue by mlopatka** [mozilla/taar-lite#24] opened 2018-05-19 08:27 UTC
Currently, it is possible for recommendations to be surfaced based on guid co-installations that are incompatible with the client's OS. This is handled elegantly by AMO whent he recommmendations are surfaced, however, the client should not be exposed to unavailable extensions. 

No obvious solution presents itself without splitting the ETL job by OS, which would mean that no recommendations are available for OS'es with few clients (to meet minimum installs thresholds in place for privacy).

@birdsarah @crankycoder Let's discuss a strategy for providing a good experience to all platforms.

**Comment by mlopatka** [comment] 2018-05-19 08:28
It occurs to me that some kind of cross-geo cross-os solution may generalize to solving both this issue and #7.

**Comment by crankycoder** [comment] 2018-08-28 17:42
This is a duplicate of #35. Filtering by user-agent string would solve this.

**Closed by crankycoder** 2018-08-28 17:42 UTC
Labels: enhancement
